export const CONNECT_WITH_WALLET = "CONNECT_WITH_WALLET";
export const lOGIN = "LOGIN";
export const FRIEND_LIST = "FRIEND_LIST";

export const CURRENT_FRIEND_DETAIL = "CURRENT_FRIEND_DETAIL";
export const FRIEND_MSG = "FRIEND_MSG";
export const SEARCH_USER = "SEARCH_USER";

export const LOADING = "LOADING";

export const ERROR_CONNECT_WITH_WALLET = "ERROR_CONNECT_WITH_WALLET";
export const ERROR_AUTH = "ERROR_AUTH";
export const ERROR_FRIEND_LIST = "ERROR_FRIEND_LIST";
export const ERROR_FRIEND_MSG = "ERROR_FRIEND_MSG";
